%---------------------------------------------------------------------
% LIST of all features.
%
% <<DO NOT EDIT unless adding or removing features>>
%
% instead, use 'neural_parameters.m' to set the feature set or 
% pass as input argument to 'generate_all_features.m'
%---------------------------------------------------------------------
FEATURE_SET_ALL={ ...
    'spectral_power' ...
    ,'spectral_relative_power' ...
    ,'spectral_flatness' ...
    ,'spectral_diff' ...    
    ,'spectral_entropy' ...
    ,'spectral_edge_frequency' ...
    ,'FD' ...
    ,'amplitude_total_power' ...
    ,'amplitude_SD' ...                
    ,'amplitude_skew' ...            
    ,'amplitude_kurtosis' ...                
    ,'amplitude_env_mean' ...    
    ,'amplitude_env_SD' ...        
    ,'connectivity_BSI' ...
    ,'connectivity_corr' ...    
    ,'connectivity_coh_mean' ...
    ,'connectivity_coh_max' ...
    ,'connectivity_coh_freqmax' ...
    ,'rEEG_mean' ...
    ,'rEEG_median' ...
    ,'rEEG_lower_margin' ...
    ,'rEEG_upper_margin' ...
    ,'rEEG_width' ...
    ,'rEEG_SD' ...
    ,'rEEG_CV' ...
    ,'rEEG_asymmetry' ...
    ,'IBI_length_max' ...
    ,'IBI_length_median' ...    
    ,'IBI_burst_prc' ... 
    ,'IBI_burst_number' ...            
                };


